var levels=[
{ "height":15,
 "layers":[
        {
         "data":[0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 2, 3, 3,,,,,,,,,,,,,, 5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 1, 1, 4,,,, 2, 3, 3, 3, 3, 3, 3, 3, 6, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 1, 1, 1,,,, 1,,,,,,,,, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 2, 3, 3, 3, 4,,, 2, 3, 4,, 1,,,,, 5,, 1,, 2, 3, 3, 3, 3, 3, 3, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 2, 3, 3, 3, 4,,,,,,,,,, 5, 1, 1, 1, 1, 1, 3, 3, 1, 1,,, 1,, 3, 3,,,, 1,,,,,,,,,,, 5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1,,,, 1, 3, 1, 1, 5,,, 1, 3, 3, 3, 3, 3, 3, 4, 7, 2, 3, 1, 4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,,, 1,,,,,,,,, 1,, 1, 1, 4,,,,, 5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4,,,,,,, 5, 1,,,,,,,,,,,,,,,,,,, 5,, 1,, 3, 3, 3, 3, 3, 3, 3, 1,, 1, 1, 1, 4,,, 2, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1,,,,,,,,,,, 1,,,, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 4,, 5,, 5,, 5,, 1,, 1,,,,,,,,,,, 1, 1, 1, 1,, 2, 1, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 3, 3, 3, 3, 3, 3, 3, 3, 4,, 1,,,,,,,,,,,,,,,,,,,,,,,,, 1,, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1,,,,,,,, 1,,, 1,,,,,,,,,,,,,,,,,,,,,,,,, 1,,,,,,,,,,,,,,,,,,,, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 4,,,, 2, 4,, 1,,, 1,,,,,,,,,,,,,,,,,,,,,,,,, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 1, 4,,,,,,,, 5, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 1, 1, 4,, 2, 4,,,,, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 0],
         "height":15,
         "width":100,
         "x":0,
         "y":0
        }, 
        {
         "height":15,
         "objects":[
                {
                 "gid":11,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":0,
                 "y":64
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":64
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1408,
                 "y":64
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1136,
                 "y":125
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1632,
                 "y":193
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2168,
                 "y":468
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2184,
                 "y":37
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3072,
                 "y":256
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2368,
                 "y":576
                }],
         "width":100,
         "x":0,
         "y":0
        }, 
        {
         "height":15,
         "objects":[
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1920,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2304,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2560,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2624,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2688,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2752,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2816,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2880,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2944,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2304,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3392,
                 "y":576
                }, 
                {
                 "gid":22,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1152,
                 "y":512
                }, 
                {
                 "gid":23,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3520,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2496,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2496,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2496,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2560,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2624,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2688,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2752,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2816,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2880,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2944,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3008,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3072,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3072,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":3072,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2048,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":2048,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1792,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1792,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1792,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1280,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1408,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1600,
                 "y":512
                }],
         "width":100,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tilesheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":11,
         "image":"charsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":21,
         "image":"collectsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "version":1,
 "width":100
}
,
{ "height":25,
 "layers":[
        {
         "data":[0,,,,,,,,,,,,, 1, 1,,,,,, 1, 1, 1, 1, 1,,,,,,,,,,, 2, 4,, 1, 1,,,, 2, 3, 1, 1, 1, 1, 1,,,,,,, 2, 3, 3, 3, 1,,, 1, 1,,,,,, 1, 1, 1, 1, 1,,,, 2, 4,,,,,,,, 2, 1, 1,,,,,, 1, 1, 1, 1, 1,,,,,,,,,,,,,, 1, 1, 3, 4,,,, 1, 1, 1, 1, 1, 4,,,,,, 2, 3, 3, 4,, 2, 3, 1, 1,,,,,, 1, 1, 1, 1, 1,,, 2, 3, 4,,, 1, 1,,, 1, 1, 1, 1,,,, 2, 3, 1, 1, 1, 1, 1,,,,,,,, 1,,, 2, 1, 1,,,,,,,,,,,,,,,,, 2, 3, 3, 1, 4,,, 1, 1,,,,,,,,,,, 2, 1, 3, 3, 3, 3, 1, 1, 1,,,, 2, 1, 1, 3, 3, 3, 4,,,,,, 2, 1, 1, 1, 1, 1, 1, 1,,,, 2, 3, 1, 1,,,,, 1,,, 2, 3, 3, 1, 1, 1, 1, 1,,,,, 5,,, 1, 1, 1, 3, 4,,, 1,, 2,,, 6,,,, 1,,,, 5,,,,, 1, 1, 1,,,,, 1,,,,, 2, 1, 1,, 1,,,,,,, 2, 3, 1, 1, 1,,,, 2, 1,,,,,, 1,,, 1,, 2, 3, 4,,,, 1, 1,,,,,,, 1, 3, 4,,,, 1,, 1, 1,,,, 1,,,, 1, 1,,,,,,, 1,,,,,, 1,,, 1, 4,,, 1, 3, 3, 3, 1,,, 2, 3, 3, 3, 3, 1,,, 2, 4,, 1,,, 1, 1, 4,,,,, 1, 1,,,,,,,, 1,,,,,, 1,,, 1,,,, 2, 3, 3, 1,,, 2, 3, 3, 3, 3, 3, 1, 4,,,,, 1,, 1, 1,,,,,,, 1,,,,, 1,,,,,,,,,, 1,,, 1, 3, 3, 3, 3, 3,, 1,,,,, 1,,,,,, 2, 3, 3, 3, 1, 1,, 1,,,,, 1,,,, 2, 4,, 1,,,,, 2, 1,,,, 1,,, 1,, 1, 1, 1, 1, 3, 4,,,,, 7,,,, 2, 1, 1,, 1,, 1,, 1, 1,,,,,,,,,,, 2, 3, 3, 3, 3, 1,, 1,, 1,,,,, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1,,,, 1, 1, 1,, 0],
         "height":25,
         "width":25,
         "x":0,
         "y":0
        }, 
        {
         "height":25,
         "objects":[
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":576
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":1216
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":768,
                 "y":960
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":1088
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":1472
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":192,
                 "y":1216
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":960
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":128,
                 "y":832
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":704,
                 "y":256
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":64
                }, 
                {
                 "gid":12,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":192,
                 "y":320
                }, 
                {
                 "gid":11,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":0,
                 "y":512
                }],
         "width":25,
         "x":0,
         "y":0
        }, 
        {
         "height":25,
         "objects":[
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1408,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1280,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1280,
                 "y":768
                }, 
                {
                 "gid":22,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":64
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1152,
                 "y":64
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":256
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1024,
                 "y":256
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1152,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":832,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":896,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1088,
                 "y":896
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1088,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1280,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1152,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1088,
                 "y":1344
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1024,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":896,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":832,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":512,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":1344
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":1344
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":704,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":768,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":832,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":896,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":960,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":832,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":768,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":768,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":704,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":64
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":704,
                 "y":64
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":192,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":0,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":320,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":512,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":640,
                 "y":576
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":576,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":512,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":320,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":64,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":128,
                 "y":1088
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":320,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":64,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":128,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":1280
                }, 
                {
                 "gid":23,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":768,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1088,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1088,
                 "y":1600
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1152,
                 "y":1600
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1600
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1216,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1280,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1344,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1408,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":448,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":384,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":320,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":192,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":128,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":64,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":64,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":64,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":128,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":192,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":256,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1408,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":896
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":896
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":960
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1024
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1088
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1344
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1408
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1536,
                 "y":1600
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1600
                }, 
                {
                 "gid":21,
                 "height":0,
                 "properties":
                    {

                    },
                 "width":0,
                 "x":1472,
                 "y":1088
                }],
         "width":25,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tilesheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":11,
         "image":"charsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":21,
         "image":"collectsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "version":1,
 "width":25
}
,
{ "height":25,
 "layers":[
        {
         "data":[0,,,,,,,,, 1, 1,,,,,,,,,,,,,, 1,,,,,,,,,, 1, 1,,,,,,,,,,,,,, 1,,,,,,,, 2, 3, 1, 1, 3, 3, 4,,,,,,,,,,, 1, 3, 3, 3, 4,,,, 1, 1, 1, 1, 1, 1,,,,,,,,,, 2, 3, 1, 1, 1, 1, 1,,,,,, 1, 1,,,,, 2, 3, 4,,,,, 1, 1, 1,,,,,,,,,, 1, 1,,,,, 1, 1, 1, 4,,,,,, 1, 3, 4,,,,,,,, 1, 1, 3, 3, 4,,,, 1, 1, 4,,,,, 1, 1, 1, 3, 4,,, 2, 3, 3, 1, 1, 1, 1,,,,,, 1, 1, 3, 3, 3, 3, 1,,,,,,, 1, 1, 1, 1, 1,,,, 2, 4,,, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,, 6,,,, 1, 1,,,,,,,,,, 3, 3, 4,,,,,,, 2, 3, 3, 4,,,,,,,,,,,,, 1, 1, 1,,,,,,, 1, 1, 1, 1,,,,,, 2, 3,,,, 2, 3, 1, 1, 1,,,,,,, 1, 1, 1, 1, 3, 4,,,, 1, 1,,,, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1,,,, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,,,, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,, 7,,,,,, 2, 3, 1, 1, 1, 1, 1, 1, 1,,,,,,,,,,, 2, 4,,,,, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4,,, 2, 4,,,, 2, 1, 1,,,,,,,,,,,,,, 1, 1, 3, 3, 1, 1,,,, 1, 1, 1, 3, 4,,,,,,,,,,,, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1,,, 2, 4,,,,,,,, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,,, 1, 1,,,, 2, 4,,,,,,,,,,,,,,,,,,,,,,,, 1, 1,,,,,,,,,,,,,,,,,,,,,,,,,,,, 3, 3, 3, 3, 3, 4,,,,, 2, 3, 4,,,,,, 2, 4,,,, 2, 4, 1, 1, 1, 1, 1, 1,,,,, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1,,,, 1, 1],
         "height":25,
         "width":25,
         "x":0,
         "y":0
        }, 
        {
         "height":0,
         "objects":[
                {
                 "gid":11,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":14,
                 "y":126
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":470,
                 "y":1106
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":484,
                 "y":734
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":232,
                 "y":732
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1314,
                 "y":806
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1306,
                 "y":362
                }, 
                {
                 "gid":12,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":966,
                 "y":1476
                }],
         "width":0,
         "x":0,
         "y":0
        }, 
        {
         "height":0,
         "objects":[
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":960,
                 "y":256
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1024,
                 "y":256
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1088,
                 "y":256
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1152,
                 "y":320
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1216,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1408,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1472,
                 "y":192
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":960,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":896,
                 "y":512
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":768,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":704,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":768,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":832,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":512,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":448,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":384,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":64,
                 "y":384
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":0,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":64,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":128,
                 "y":640
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":256,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":320,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":384,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":448,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":832,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":896,
                 "y":768
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1088,
                 "y":960
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1024,
                 "y":960
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1408,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1344,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1472,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1536,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1216,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1152,
                 "y":704
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1280,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1408,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1472,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":448,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":512,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":512,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":128,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":192,
                 "y":1152
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":384,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":448,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":512,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1344,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1408,
                 "y":1280
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1024,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1088,
                 "y":1216
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":832,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":896,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1024,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1088,
                 "y":1536
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1472,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1536,
                 "y":1472
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1280,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":1344,
                 "y":448
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":192,
                 "y":832
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":960,
                 "y":1536
                }, 
                {
                 "gid":22,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":0,
                 "y":384
                }, 
                {
                 "gid":23,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":704,
                 "y":128
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":64,
                 "y":1088
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":256,
                 "y":1088
                }, 
                {
                 "gid":21,
                 "height":64,
                 "properties":
                    {

                    },
                 "width":64,
                 "x":320,
                 "y":1088
                }],
         "width":0,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tilesheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":11,
         "image":"charsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":21,
         "image":"collectsheet.png",
         "imageheight":64,
         "imagewidth":640,
         "margin":0,
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "version":1,
 "width":25
}
,
];
